/*
 * File: app/controller/AlertsController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PeopleMover.controller.AlertsController', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.MessageBox'
    ],

    config: {
        views: [
            'TrolleyAlerts'
        ],

        control: {
            "trolleyalerts #bAlert": {
                tap: 'onButtonTap'
            }
        }
    },

    onButtonTap: function(button, e, eOpts) {
                                          // Success

                                                var successCallback = function(resp, ops) {


                                                     var modifyalertfield = Ext.getCmp('alertfield');


                                                    var jsonResp = Ext.JSON.decode(resp.responseText);
                                                       //Ext.Msg.alert("Info","message:"+jsonResp.message);
                                                    modifyalertfield.setValue(jsonResp.message);

                //                                     //get back
                //                                          mainView.pop();

                //                                 //     // Hide login panel
                //                                      form.hide();


                                                };
                                             // Failure
                                                var failureCallback = function(resp, ops) {

                                                   var jsonResp = Ext.JSON.decode(resp.responseText);
                                                              Ext.Msg.alert("Info","Not Alert");



                                                };



                                        var alertfield = Ext.getCmp('alertfield');
                                        var token = localStorage.getItem('ppmtoken');
                                        if(!alertfield.getReadOnly())
                                            {
                                             var message = alertfield.getValue();


                                              var callparams = {
                                                                    "token":token,
                                                                     "message": message
                                                                    };
                                                //TODO: Registration using server-side authentication service






                                                                    Ext.Ajax.request({
                                                                        url: "http://pm-dev.cs.fiu.edu:8080/ppmws/alert",
                                                                        /*url: "http://192.168.0.101/sendemail",*/
                                                                        method: 'POST',
                                                                        /*headers: { 'Content-Type': 'application/json' },*/
                                                                        params: callparams,
                                                                        success: successCallback,
                                                                        failure: failureCallback
                                                                    });
                                            }
    },

    launch: function() {



        /* var form = button.up('formpanel'),
                                values = form.getValues(),				// Form values
                                mainView = this.getMainView();
        */

                        // Success
                                        var successCallback = function(resp, ops) {


                                             var alertfield = Ext.getCmp('alertfield');


                                            var jsonResp = Ext.JSON.decode(resp.responseText);
                                               //Ext.Msg.alert("Info","message:"+jsonResp.message);
                                            var alert = jsonResp.message;
                                            alertfield.setValue(jsonResp.message);

                                            if(alert!=="Not Defined Alert")
                                                {
                                   var alertbutton = Ext.getCmp('myTabPanel').getTabBar().getComponent(3);
                                                        //Ext.getCmp('btrolleyalerts');
                                                        //Ext.create('widget.mainview').down('#btrolleyalerts');
                                                    alertbutton.setBadgeText("New");

                                                }

        //                                     //get back
        //                                          mainView.pop();

        //                                 //     // Hide login panel
        //                                      form.hide();


                                        };

                                        // Failure
                                        var failureCallback = function(resp, ops) {

                                           var jsonResp = Ext.JSON.decode(resp.responseText);
                                                      Ext.Msg.alert("Info","Not Defined Alert");



                                        };
                                        //TODO: Registration using server-side authentication service






                                                            Ext.Ajax.request({
                                                                url: "http://pm-dev.cs.fiu.edu:8080/ppmws/alert",
                                                                /*url: "http://192.168.0.101/sendemail",*/
                                                                method: 'POST',
                                                                /*headers: { 'Content-Type': 'application/json' },*/
                                                                /*params: callparams,*/
                                                                success: successCallback,
                                                                failure: failureCallback
                                                            });
    }

});